### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ViniciusdSC** [ViniciusdSC/garcom-digital-web#1]
### Database
- [ ] modelo de dados
- [ ] migrations
- [ ] factories
- [ ] seeds

### CRUD
- [ ] usuário
- [ ] estabelecimento
- [ ] mesa
- [ ] produto

### TELAS ESPECIFICAS
- [ ] feed do estabelecimento
- [ ] lista de pedidos
- [ ] lista de contas

### Funções especificas
- [ ] notificação

### API
- [ ] liberar mesa
- [ ] entrar na mesa
- [ ] fazer pedido
- [ ] pedir a conta
